version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install"
  build:
    commands:
      - echo "Packaging application"
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/*
